"""create provider services table

Revision ID: 4cd5a9418bef
Revises: ec088875140f
Create Date: 2026-09-06 11:19:01.738847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd5a9418bef'
down_revision: Union[str, Sequence[str], None] = 'ec088875140f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('BIKE', 'AUTO', 'CAB', name='servicetype'), nullable=False),
    sa.Column('vehicle_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operating_city', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_services')
    # ### end Alembic commands ###
